spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/admin
      database: ${MONGO_DATABASE}

security:
  jwt:
    access-key: ${ACCESS_KEY}
    api-key: ${API_KEY}
    plugin-key: ${PLUGIN_KEY}
  stripe:
    pb-key: ${STRIPE_PB_KEY}
    secret-key: ${STRIPE_SECRET_KEY}

sentry:
  service: ${SERVICE_DSN}
  plugin: ${PLUGIN_DSN}