server:
  port: 8222
  error:
    include-message: always

spring:
  application:
    name: minecraft
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  profiles:
    active: ${PROFILE}

reactor:
  ipc:
    netty:
      workerCount: 1

disk:
  path: /disk