server:
  port: 8221
  error:
    include-message: Always

spring:
  application:
    name: plugin
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    profiles:
      active: ${PROFILE}

rapidapi:
  key: ${RAPID_KEY}

images:
  path: /images