server:
  port: 8223
  error:
    include-message: Always

spring:
  application:
    name: version-service
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  profiles:
    active: ${PROFILE}

storage:
  disk: /versions